var items = new Map([
    [1, { "name": "Heavy shirt printing letters", "stars": 4.5, "price": "$10.40", "image":"../images/pro10.webp" }],
    [2, { "name": "Men Letter Graphic Raglan Hoodie", "stars": 4.0, "price": "$27.00", "image":"../images/pro11.webp" }],
    [3, { "name": "Manfinity Sporsity Hooded Jacket", "stars": 4.0, "price": "$26.99", "image":"../images/pro12.webp" }],
    [4, { "name": "Men Letter Graphic Raglan Sleeve", "stars": 3.5, "price": "$13.48", "image":"../images/pro13.webp" }],
    [5, { "name": "Manfinity Hypemode Pocket Hoodie", "stars": 4.0, "price": "$14.83", "image": "../images/pro14.webp" }],
    [6, { "name": "Manfinity Homme awstring Hoodie", "stars": 4.5, "price": "$17.49", "image": "../images/pro15.webp" }],
    [7, { "name": "Manfinity Homme Pressed Design", "stars": 5.0, "price": "$19.16", "image": "../images/pro16.webp" }],
    [8, { "name": "Men Letter Rawstring Hoodie", "stars": 3.5, "price": "$20.21", "image": "../images/pro17.webp" }],
    [9, { "name": "Men Letter Graphic Raglan Sleeve", "stars": 5.0, "price": "$27.00", "image": "../images/pro18.webp" }],
    [10, { "name": "Manfinity Homme Men Letter Graph", "stars": 4.0, "price": "$26.00", "image": "../images/pro19.webp" }],
    [11, { "name": "Manfinity Homme Drawstring Hoodie", "stars": 4.0, "price": "$26.99", "image": "../images/pro20.webp" }],
    [12, { "name": "Manfinity Hypemode Men Slogan", "stars": 3.5, "price": "$13.48", "image": "../images/pro21.webp" }],
    [13, { "name": "Manfinity Homme Men Letter & Flor", "stars": 4.0, "price": "$17.65", "image": "../images/pro22.webp" }],
    [14, { "name": "Men's Cartoon Print Hoodie Sweatshirt", "stars": 4.5, "price": "$18.49", "image": "../images/pro23.webp" }],
    [15, { "name": "Manfinity EMRG Men Cotton", "stars": 5.0, "price": "$19.16", "image": "../images/pro24.webp" }],
    [16, { "name": "Manfinity White Men Hoodie", "stars": 3.5, "price": "$20.21", "image": "../images/pro25.webp" }],
    [17, { "name": "Men black Hooded Jacket", "stars": 4.0, "price": "$13.48", "image": "../images/pro26.webp" }],
    [18, { "name": "Men Letter light blue Hoodie", "stars": 4.5, "price": "$14.83", "image": "../images/pro27.webp" }],
    [19, { "name": "Men Letter Hooded Jacket", "stars": 3.5, "price": "$17.49", "image": "../images/pro28.webp" }],
    [20, { "name": "Manfinity brown Men Cotton", "stars": 5.0, "price": "$19.16", "image": "../images/pro29.webp" }],


    [21, { "name": "Cartoon Graphic Thermal Hoodie", "stars": 4.5, "price": "$10.40", "image": "../images/wpro1.webp" }],
    [22, { "name": "Zip Up Drop Shoulder Drawstring Hooded", "stars": 4.0, "price": "$27.00", "image": "../images/wpro2.webp" }],
    [23, { "name": "2 In 1 Simple Round Neck Sweater", "stars": 4.0, "price": "$26.99", "image": "../images/wpro3.webp" }],
    [24, { "name": "LUNE Double Breasted Lapel Neck", "stars": 3.5, "price": "$13.48", "image": "../images/wpro4.webp" }],
    [25, { "name": "Patched Detail Drop Shoulder Half", "stars": 4.0, "price": "$14.83", "image": "../images/wpro5.webp" }],
    [26, { "name": "Women's Drop Shoulder Sweatshirt", "stars": 4.5, "price": "$17.49", "image": "../images/wpro6.webp" }],
    [27, { "name": "Slogan Graphic Lined Sweatshirt", "stars": 5.0, "price": "$19.16", "image": "../images/wpro7.webp" }],
    [28, { "name": "Cable Knit Drop Shoulder Sweater", "stars": 3.5, "price": "$20.21", "image": "../images/wpro8.webp" }],
    [29, { "name": "Solid Drop Shoulder Split Hem Sweater", "stars": 5.0, "price": "$27.00", "image": "../images/wpro9.webp" }],
    [30, { "name": "LUNE Color Block Drop Shoulder Sweater", "stars": 4.5, "price": "$26.00", "image": "../images/wpro10.webp" }],
    [31, { "name": "LUNE Open Front Overcoat", "stars": 4.0, "price": "$26.99", "image": "../images/wpro11.webp" }],
    [32, { "name": "Kangaroo Pocket Solid Hoodie", "stars": 3.5, "price": "$13.48", "image": "../images/wpro12.webp" }],
    [33, { "name": "Letter Graphic Thermal Lined Sweatshirt", "stars": 4.0, "price": "$17.65", "image": "../images/wpro13.webp" }],
    [34, { "name": "Dazy-Less Cable Knit Drop Shoulder Sweater", "stars": 4.0, "price": "$18.49", "image": "../images/wpro14.webp" }],
    [35, { "name": "Coolane Letter Pattern Drop Shoulder", "stars": 5.0, "price": "$19.16", "image": "../images/wpro15.webp" }],
    [36, { "name": "Colorblock Button Detail Tee", "stars": 4.0, "price": "$20.21", "image": "../images/wpro16.webp" }],
    [37, { "name": "Long Sleeve T-shirt With Slogan Print", "stars": 4.5, "price": "$13.48", "image": "../images/wpro17.webp" }],
    [38, { "name": "Floral Print Kangaroo Pocket Drawstring", "stars": 4, "price": "$14.83", "image": "../images/wpro18.webp" }],
    [39, { "name": "Slogan Graphic Thermal Lined Sweatshirt", "stars": 4.5, "price": "$17.49", "image": "../images/wpro19.webp" }],
    [40, { "name": "Floral Print Thermal Lined Sweatshirt", "stars": 5, "price": "$19.16", "image": "../images/wpro20.webp" }],



    [41, { "name": "Long Sleeve Plaid Irregular Skirt", "stars": 4.5, "price": "$10.40", "image": "../images/kpro1.webp" }],
    [42, { "name": "Solid Zip Up Snap Button Puffer Coat", "stars": 4, "price": "$27.00", "image": "../images/kpro2.webp" }],
    [43, { "name": "KDOMO Tween Girls' Plush Casu", "stars": 4, "price": "$26.99", "image": "../images/kpro3.webp" }],
    [44, { "name": "Toddler Girls Cloud & Rainbow", "stars": 3.5, "price": "$13.48", "image": "../images/kpro4.webp" }],
    [45, { "name": "Flap Pocket Vest Puffer Coat", "stars": 4, "price": "$14.83", "image": "../images/kpro5.webp" }],
    [46, { "name": "Zip Up Hooded Teddy Coat Without Sweater", "stars": 4.5, "price": "$17.49", "image": "../images/kpro6.webp" }],
    [47, { "name": "Plaid Print Letter Patched Jacket", "stars": 5, "price": "$19.16", "image": "../images/kpro7.webp" }],
    [48, { "name": "Fuzzy Trim Hooded Teddy Lined Puffer Coat", "stars": 4.5, "price": "$20.21", "image": "../images/kpro8.webp" }],
    [49, { "name": "Letter Printed Warm Sporty Sweatshirt", "stars": 5, "price": "$27.00", "image": "../images/kpro9.webp" }],
    [50, { "name": "Fuzzy Trim Hooded Puffer Coat", "stars": 4, "price": "$26.00", "image": "../images/kpro10.webp" }],
    [51, { "name": "Casual Hooded Sweatshirt", "stars": 4, "price": "$26.99", "image": "../images/kpro11.webp" }],
    [52, { "name": "Borg Collar Cardigan & Flare Leg Pants", "stars": 3.5, "price": "$13.48", "image": "../images/kpro12.webp" }],
    [53, { "name": "Fuzzy Trim Hooded Thermal L", "stars": 4, "price": "$17.65", "image": "../images/kpro13.webp" }],
    [54, { "name": "Girl Zip Up Hooded Puffer Coat", "stars": 4.5, "price": "$18.49", "image": "../images/kpro14.webp" }],
    [55, { "name": "Warm Hooded padded Jacket", "stars": 5, "price": "$19.16", "image": "../images/kpro15.webp" }],
    [56, { "name": "Dinosaur Embroidery Flannel Sweatshirt", "stars": 4, "price": "$20.21", "image": "../images/kpro16.webp" }],
    [57, { "name": "Borg Collar Teddy Lined Coat", "stars": 3.5, "price": "$13.48", "image": "../images/kpro17.webp" }],
    [58, { "name": "Trim Hooded Puffer Coat", "stars": 4, "price": "$14.83", "image": "../images/kpro18.webp" }],
    [59, { "name": "Zipper Hooded Vest Puffer Coat", "stars": 4.5, "price": "$17.49", "image": "../images/kpro19.webp" }],
    [60, { "name": "Heart Print Drop Shoulder Hoodie", "stars": 5, "price": "$19.16", "image": "../images/kpro20.webp" }]

]);
